/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Views;

import Classes.HTMLImage;
import Classes.HTMLText;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JFileChooser;

/**
 *
 * @author Ross
 */
public class Template1 extends javax.swing.JFrame {

    String imageURL;
    String html;
    String pageName;
    String filePath;
    
    
    /** Creates new form Template1 */
    public Template1() {
        
        initComponents();
        
        
        
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateHtmlImage = new javax.swing.JButton();
        btnChooseFilePath = new javax.swing.JButton();
        txtTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txbBodyText1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txbBodyText2 = new javax.swing.JTextArea();
        txtImagePath = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCreateHtmlImage.setText("Create HTML image");
        btnCreateHtmlImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateHtmlImageActionPerformed(evt);
            }
        });

        btnChooseFilePath.setText("Select Image");
        btnChooseFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChooseFilePathActionPerformed(evt);
            }
        });

        txtTitle.setText("Insert Title");

        txbBodyText1.setColumns(20);
        txbBodyText1.setRows(10);
        txbBodyText1.setText("Insert Body Text");
        jScrollPane1.setViewportView(txbBodyText1);

        txbBodyText2.setColumns(20);
        txbBodyText2.setRows(5);
        txbBodyText2.setText("Inser Body Text 2");
        jScrollPane2.setViewportView(txbBodyText2);

        txtImagePath.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateHtmlImage, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChooseFilePath, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChooseFilePath)
                    .addComponent(txtImagePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(btnCreateHtmlImage)
                .addContainerGap(103, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateHtmlImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateHtmlImageActionPerformed
        
        
        HTMLText newHeader = new HTMLText("</h1>", txtTitle.getText());
        HTMLText newPara = new HTMLText("</p>", txbBodyText1.getText());
        HTMLImage newImage = new HTMLImage(txtImagePath.getText(), "the-image", 300, 325);
        HTMLText newPara2 = new HTMLText("</p>", txbBodyText2.getText());
        
        imageURL = "C:\\Users\\Ross\\Desktop\\Unity Projects\\Neon Sprites\\Tiles\\unitest.png";
        pageName = "Test2";
        filePath = "C:\\Users\\Ross\\Desktop\\HonoursTest\\";
       // HTMLImage.setImageURL(imageURL);
        html = "<!DOCTYPE html>\n" +
"\n" +
"<html>\n" +
"<head>\n" +
"\n" +
"</head>\n" +
"<body>\n" +
"\n" +
newHeader.getOpeningTag() + newHeader.getText() + newHeader.getTag() + "\n" +
"\n" +
"\n" +
newPara.getOpeningTag() + newPara.getText() + newPara.getTag() + "\n" +
"\n" +
"\n" +
"<img src=\"" + newImage.getImageURL() + "\"alt=\"" + newImage.getAlt() + "\" width=\"" + String.valueOf(newImage.getWidth()) + "\" height=\"" + String.valueOf(newImage.getHeight()) + "\">\n" +
"\n" +
newPara2.getOpeningTag() + newPara2.getText() + newPara2.getTag() + "\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"</body>\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"\n" +
"</html>";
        File f = new File(filePath + pageName + ".html");
        try
        {
        BufferedWriter bw = new BufferedWriter(new FileWriter(f));
        bw.write(html);
        bw.close();
        }
        catch (IOException e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnCreateHtmlImageActionPerformed

    private void btnChooseFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChooseFilePathActionPerformed
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File imageFile = chooser.getSelectedFile();
        String imageFilePath = imageFile.getAbsolutePath();
        txtImagePath.setText(imageFilePath);
    }//GEN-LAST:event_btnChooseFilePathActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Template1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Template1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChooseFilePath;
    private javax.swing.JButton btnCreateHtmlImage;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txbBodyText1;
    private javax.swing.JTextArea txbBodyText2;
    private javax.swing.JTextField txtImagePath;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

}
